### ISSUE TITLE
Query about the pre-trained backbone

### ISSUE THREAD

**Issue by RayYoh** [yunshin/SphericalMask#2]
Dear Authors,

Thanks for your work and open source the code. My question is about the pre-trained backbone weight. I'd like to ask what is the difference between you provided [here](https://drive.google.com/file/d/1OeHRgkEkxvPkUOrFacmNUevrrAjHW6DA/view?usp=drive_link) and the ISBNet repo provided [here](https://drive.google.com/file/d/1vIO6rQOy1QVHaWF8ie4E3q0tQbwiY0Kb/view?usp=sharing). I have tried them based on my own method but find that the backbone ISBNet provided gets worse results.

And also is there any plan to provided the code and weights for other datasets like S3DIS.

**Comment by yunshin** [comment]
Just wanted to add our conversation through email:

1) For ScanNet backbone, we trained ISBNet using their initial release with larger augmentation parameters, which you can find and manually tune in data/custom.py. We finished the pre-training when the model reached the highest mAP and use it as the current pre-trained weight. 

2)Yes, we are planning to release the config file and the weight for S3DIS as well accordingly with CVPR conference and official paper release around the time.
